### ISSUE TITLE
Wrongly applied licenses

### ISSUE THREAD

**Issue by ppisar** [DrHyde/perl-modules-IP-World#2]
lib/IP/World.pod reads:

~~~~
This module is free software; you may redistribute it and/or
modify it under the same terms as Perl 5.10.1.  For more details,
see the full text of the licenses
at L<http://www.perlfoundation.org/artistic_license_1_0>
and L<http://www.gnu.org/licenses/gpl-2.0.html>
~~~~

The first and the second sentence mismatch. Perl is licensed <https://dev.perl.org/licenses/> as "GPL version 1 or later, or Artistic 1.0 license". The minimal version of GPL differs.

Then lib/IP/World.pod continues:

~~~~
This program is distributed in the hope that it will be useful, but
it is provided 'as is' and without any express or implied warranties.
For details, see the full text of the licenses at the above URLs.
~~~~

But GPLv1 license requires:

~~~~
  1. You may copy and distribute verbatim copies of the Program's source
code as you receive it, in any medium, provided that you [...] give any
other recipients of the Program a copy of this General Public License
along with the Program. 
~~~~

It would be great if added a copy of the GPLv1 text into the distribution (preferably as a separate file).

Finally, the WIPMania database distributed in lib/auto/IP/World/ is covered by a completely different license <http://www.wipmania.com/terms/>:

~~~~
Free versions of WorldIP Databases are licensed under a Creative Commons Attribution-Noncommercial-No Derivative
Works 3.0 License (CC-BY-NC-ND, http://creativecommons.org/licenses/by-nc-nd/3.0/)
~~~~

That's not mentioned anywhere in your distribution. Namely the license requires to copy the license text or URI:

~~~~
You must include a copy of, or the Uniform Resource Identifier (URI) for, this License
with every copy of the Work You Distribute or Publicly Perform. 
~~~~

and it forbids a non-commercial use:

~~~~
You may not exercise any of the rights granted to You in Section 3 above in any manner
that is primarily intended for or directed toward commercial advantage or private monetary
compensation.
~~~~

That's in conflict with GPL. While you do not combine the two works, I think, it does not matter, but still the users should be know it by properly declaring the license terms.

Please do not take this complain as an attack. I'm not afiliated with the copyright holders of this software and data. I only wanted to package it for Fedora and discovered these issues. So it would be great to correct them to prevent others from falling into the same trap (Fedora does not allow CC-BY-NC-ND license).

**Comment by DrHyde** [comment]
I hate this sort of problem, but it *is* important so thank you for bringing it to my attention :-)

Wipmania have some extra terms that say that despite the -NC- bit of that you can use it commercially with some restrictions, so maybe Fedora will accept that. And it turns out that the wipmania project is dead and no longer updating, so I'll release an update that fixes these issues, but also deprecates use of the whole thing.

The simplest way forward is, I think, for me to re-licence under ARTISTIC-only, allowed under the "same as Perl 5.10.1" licence. That gets rid of the conflict.

**Comment by DrHyde** [comment]
See https://github.com/DrHyde/perl-modules-IP-World/commit/c589512, which will become version 0.42 momentarily.

**Comment by ppisar** [comment]
Thank you for handling it. Though it does not make it any better for Fedora.
